### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by lawrence-laz** [nix21/multi-caret-booster#1]
Hi, great extension! Would it be difficult to add this to VS2022?

**Comment by nix21** [comment]
Hi, in Visual Studio 2022 Copy & Paste funcionality works as expected even without this extension. So I don't think it is really needed.  The only missing funcionality in VS2022 is a feature "selection to sequence". To create a separate extension that would contain only this command is currently in my if-I-get-bored TODO list :-) So if this command is what you lack, I might be able to push it at the top of the list, if you want...

**Comment by lawrence-laz** [comment]
Oh, I was not aware of that! I mostly missed multi caret copy/paste with different values per line, which this extension solved. So thanks for that! :)
